name: Release Graphql Schema
on:
  pull_request:
    branches: [main]
    types: [closed]
    paths: [app/graphql/**]
jobs:
  release_graplqh_schema:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
      - name: Graphql schema dump
        run: |
          bundle exec rails graphql:schema:dump
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump GitHub token
        run: echo '${{ toJSON(github.token) }}'
      - name: Upload graphql schema to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: tmp/graphql/*.graphql
          overwrite: true
          file_glob: true
