name: Release Graphql Schema
on:
  pull_request:
    branches: [main]
    types: [closed]
    paths: [tmp/graphql/**]
jobs:
  release_graplqh_schema:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Upload graphql schema to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/graphql/*.graphql
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
